# Generated by Django 4.0.4 on 2022-06-29 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='campo_leido',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='cuerpo',
            field=models.CharField(max_length=200000000),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='emisor',
            field=models.CharField(max_length=200000000),
        ),
    ]
